sys_includes = ["signal.h"]
include_guard = "_SYS_EPOLL_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=dragonos" = "__dragonos__"
"target_pointer_width=64" = "__LP64__"

[enum]
prefix_with_name = true
