sys_includes = ["stdint.h", "sys/types.h"]
include_guard = "_DLIBC_SIGNAL_H"
trailer = "#include <bits/signal.h>"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=redox" = "__dragonos__"

[enum]
prefix_with_name = true
