sys_includes = ["stdarg.h", "sys/types.h"]
include_guard = "_DLIBC_FCNTL_H"
trailer = "#include <bits/fcntl.h>"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os=dragonos" = "__dragonos__"

[enum]
prefix_with_name = true
