sys_includes = ["sys/types.h", "stdint.h", "stddef.h"]
include_guard = "_DLIBC_TIME_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[defines]
"target_os = dragonos" = "__dragonos__"
