sys_includes = ["stddef.h", "alloca.h"]
include_guard = "_DLIBC_STDLIB_H"
trailer = "#include <bits/stdlib.h>"
language = "C"
style = "Type"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[fn]
no_return = "__attribute__((noreturn))"
