sys_includes = ["stdint.h", "sys/types.h"]
include_guard = "_SYS_MMAN_H"
trailer = "#include <bits/sys/mman.h>"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[defines]
"target_os = dragonos" = "__dragonos__"

[enum]
prefix_with_name = true
