sys_includes = ["bits/assert.h"]
include_guard = "_DLIBC_ASSERT_H"
language = "C"
style = "Tag"
no_includes = true
cpp_compat = true

[enum]
prefix_with_name = true

[fn]
no_return = "__attribute__((noreturn))"
